services:
  mariadb:
    image: mariadb:10.6
    container_name: owncloud_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - owncloud_net

  redis:
    image: redis:7
    container_name: owncloud_redis
    restart: always
    networks:
      - owncloud_net

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: owncloud_keycloak
    restart: always
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8960:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    networks:
      - owncloud_net

  oidc-web:
    image: nginx:alpine
    container_name: owncloud_oidc_web
    restart: always
    ports:
      - "8958:80"
    volumes:
      - ./owncloud_oidc.html:/usr/share/nginx/html/index.html:ro
    networks:
      - owncloud_net

  owncloud:
    image: owncloud/server:10.15
    container_name: owncloud_server
    restart: always
    depends_on:
      - mariadb
      - redis
      - keycloak
    ports:
      - "8959:8080"
    environment:
      OWNCLOUD_DOMAIN: "localhost:8959"
      OWNCLOUD_OVERWRITE_CLI_URL: "http://localhost:8959"
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: owncloud
      OWNCLOUD_DB_HOST: owncloud_mariadb
      OWNCLOUD_DB_PREFIX: oc_
      OWNCLOUD_ADMIN_USERNAME: admin
      OWNCLOUD_ADMIN_PASSWORD: ChangeThisPassword
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: owncloud_redis
      OWNCLOUD_VOLUME_FILES: /mnt/data/files
      OWNCLOUD_TRUSTED_DOMAINS: "127.0.0.1,localhost,host.docker.internal,owncloud.pandoratech.ae"
    volumes:
      - ./data:/mnt/data
      - owncloud_apps:/var/www/owncloud/apps
      - ./config:/mnt/data/config
    networks:
      - owncloud_net

networks:
  owncloud_net:
    driver: bridge

volumes:
  owncloud_apps:
    driver: local
